# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json
---
version: "2"

formatters:
  enable: [gci, gofumpt, gofmt, goimports]
  settings:
    gci: { sections: [standard, default, localmodule] }
    gofumpt:
      module-path: github.com/kjanat/dprint-plugin-shfmt
      extra: { group-params: true }
    goimports: { local-prefixes: [github.com/kjanat/dprint-plugin-shfmt] }

linters:
  default: standard
  enable: [revive, gocritic, goconst, nakedret, tagalign]
