// Code generated by go generate; DO NOT EDIT.

package main

import "github.com/kjanat/dprint-plugin-shfmt/dprint"

var generatedConfigurationResolverSpec = dprint.ConfigResolverSpec[configuration]{
	UInt32Fields: []dprint.UInt32ConfigFieldSpec[configuration]{
		{
			Key:                 "indentWidth",
			DefaultValue:        2,
			AllowGlobalOverride: true,
			Get: func(config configuration) uint32 {
				return config.IndentWidth
			},
			Set: func(config *configuration, value uint32) {
				config.IndentWidth = value
			},
		},
	},
	BoolFields: []dprint.BoolConfigFieldSpec[configuration]{
		{
			Key:                 "useTabs",
			DefaultValue:        false,
			AllowGlobalOverride: true,
			Get: func(config configuration) bool {
				return config.UseTabs
			},
			Set: func(config *configuration, value bool) {
				config.UseTabs = value
			},
		},
		{
			Key:                 "binaryNextLine",
			DefaultValue:        false,
			AllowGlobalOverride: false,
			Get: func(config configuration) bool {
				return config.BinaryNextLine
			},
			Set: func(config *configuration, value bool) {
				config.BinaryNextLine = value
			},
		},
		{
			Key:                 "switchCaseIndent",
			DefaultValue:        false,
			AllowGlobalOverride: false,
			Get: func(config configuration) bool {
				return config.SwitchCaseIndent
			},
			Set: func(config *configuration, value bool) {
				config.SwitchCaseIndent = value
			},
		},
		{
			Key:                 "spaceRedirects",
			DefaultValue:        false,
			AllowGlobalOverride: false,
			Get: func(config configuration) bool {
				return config.SpaceRedirects
			},
			Set: func(config *configuration, value bool) {
				config.SpaceRedirects = value
			},
		},
		{
			Key:                 "funcNextLine",
			DefaultValue:        false,
			AllowGlobalOverride: false,
			Get: func(config configuration) bool {
				return config.FuncNextLine
			},
			Set: func(config *configuration, value bool) {
				config.FuncNextLine = value
			},
		},
		{
			Key:                 "minify",
			DefaultValue:        false,
			AllowGlobalOverride: false,
			Get: func(config configuration) bool {
				return config.Minify
			},
			Set: func(config *configuration, value bool) {
				config.Minify = value
			},
		},
		{
			Key:                 "experimentalZsh",
			DefaultValue:        true,
			AllowGlobalOverride: false,
			Get: func(config configuration) bool {
				return config.ExperimentalZsh
			},
			Set: func(config *configuration, value bool) {
				config.ExperimentalZsh = value
			},
		},
	},
	KnownKeys: []string{
		"indentWidth",
		"useTabs",
		"binaryNextLine",
		"switchCaseIndent",
		"spaceRedirects",
		"funcNextLine",
		"minify",
		"experimentalZsh",
		"locked",
	},
}
