name: release

on:
  push: { tags: ["[0-9]+.[0-9]+.[0-9]+*"] }
  workflow_dispatch:

permissions: { contents: write }

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with: { fetch-depth: 0 }

      - name: Setup mise and install tools
        uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1
        with: { install: true }

      - name: Run tests
        run: mise run test

      - name: Publish release
        run: mise run release
        env: { GITHUB_TOKEN: "${{ github.token }}" }
